apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: java-heap-collector
  namespace: <needed namespace>
  labels:
    k8s-app: java-heap-collector
spec:
  selector:
    matchLabels:
      name: java-heap-collector
  template:
    metadata:
      labels:
        name: java-heap-collector
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      containers:
      - name: java-heap-collector
        image: <your registry>
        env:
        - name: S3bucket
          value: <bucket name>
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: dumps
          mountPath: /dumps/
      terminationGracePeriodSeconds: 30
      volumes:
      - name: dumps
        hostPath:
          path: /dumps/
